[package]
name = "cadence-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rodio = { version = "0.20", features = ["symphonia-all"] }
serde = { version = "1.0", features = ["derive"] }
